# Generated by Django 5.1.7 on 2025-06-13 17:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_fabricante_remove_fornecedor_inscricao_estadual'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Fabricante',
        ),
    ]
