# Generated by Django 5.1.7 on 2025-06-13 17:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_delete_fabricante'),
    ]

    operations = [
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('descricao', models.TextField()),
                ('preco', models.DecimalField(decimal_places=2, max_digits=10)),
                ('imagem', models.ImageField(blank=True, null=True, upload_to='produtos/')),
                ('quantidade_estoque', models.PositiveIntegerField()),
                ('fornecedor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='core.fornecedor')),
            ],
        ),
    ]
